Repository kubeflow/pytorch-operator, pull requests merged in 2018-09, with the labels that each got.

#59 Adding CI tests to v1alpha2 version
  Dockerfile
  build_image.sh
  examples/cifar10/README.md
  examples/cifar10/configmap_cifar.yaml
  examples/cifar10/pytorchjob_cifar.yaml
  examples/dist-mnist/Dockerfile
  examples/dist-mnist/Makefile
  examples/dist-mnist/README.md
  examples/dist-mnist/dist_mnist.py
  examples/dist-mnist/v1alpha1/pytorch_job_mnist.yaml
  examples/dist-mnist/v1alpha2/pytorch_job_mnist.yaml
  examples/dist-sendrecv/Dockerfile
  examples/dist-sendrecv/README.md
  examples/dist-sendrecv/dist_sendrecv.py
  examples/dist-sendrecv/v1alpha1/pytorch_job_sendrecv.yaml
  examples/dist-sendrecv/v1alpha2/pytorch_job_sendrecv.yaml
  examples/v1alpha2/dist-mnist/Dockerfile
  examples/v1alpha2/dist-mnist/Makefile
  examples/v1alpha2/dist-mnist/README.md
  examples/v1alpha2/dist-mnist/dist_mnist.py
  examples/v1alpha2/dist-sendrecv/Dockerfile
  examples/v1alpha2/dist-sendrecv/README.md
  examples/v1alpha2/dist-sendrecv/dist_sendrecv.py
  scripts/build.sh
  scripts/run-tests-v1alpha1.sh
  scripts/run-tests-v1alpha2.sh
  scripts/setup-kubeflow.sh
  test/e2e/v1alpha1/main.go
  test/e2e/v1alpha2/main.go
  test/workflows/components/workflows.jsonnet
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XL

#61 Adding option for restricting operator scope to namespace level
  cmd/pytorch-operator.v2/app/options/options.go
  cmd/pytorch-operator.v2/app/server.go
  pkg/controller.v2/pytorch/controller_test.go
  pkg/controller.v2/pytorch/informer.go
Labels: approved, lgtm, size/S

#62 Compatibility with upstream controller changes
  Gopkg.lock
  pkg/controller.v2/pytorch/controller.go
  pkg/controller.v2/pytorch/controller_test.go
  pkg/controller.v2/pytorch/pod.go
  vendor/github.com/kubeflow/tf-operator/pkg/controller.v2/jobcontroller/jobcontroller.go
Labels: approved, lgtm, size/S

#63 Porting minor fixes from TF
  pkg/apis/pytorch/v1alpha2/types.go
  pkg/controller.v2/pytorch/pod.go
  pkg/controller.v2/pytorch/status.go
Labels: approved, lgtm, size/S

#64 Adding corev1 scheme to Events
  Gopkg.lock
  cmd/pytorch-operator.v2/app/server.go
  vendor/github.com/kubeflow/tf-operator/pkg/controller.v2/jobcontroller/pod.go
Labels: approved, lgtm, size/XS

#65 Adding cleanpodpolicy-all test
  scripts/v1alpha1/run-defaults.sh
  scripts/v1alpha2/run-cleanpodpolicy-all.sh
  scripts/v1alpha2/run-defaults.sh
  test/e2e/v1alpha2/cleanpolicy_all.go
  test/e2e/v1alpha2/defaults.go
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#71 Mark Job failed when spec is invalid
  cmd/pytorch-operator/app/server.go
  pkg/controller.v2/pytorch/job.go
  pkg/trainer/replicas.go
  vendor/github.com/kubeflow/tf-operator/pkg/util/k8sutil/client.go
  vendor/github.com/kubeflow/tf-operator/pkg/util/k8sutil/k8sutil.go
Labels: approved, lgtm, size/L

#72 Build check added to travis
  .travis.yml
  Gopkg.lock
Labels: approved, lgtm, size/XS

#74 Gloo support added
  examples/gloo/Dockerfile
  examples/gloo/dist_mnist.py
  examples/gloo/v1alpha2/pytorch_job_mnist.yaml
Labels: approved, lgtm, size/L

#73 Distributed Data Parallel Example
  examples/mnist-ddp/cpu/Dockerfile
  examples/mnist-ddp/cpu/mnist_DDP_CPU.py
  examples/mnist-ddp/cpu/v1alpha2/job_mnist_DDP_CPU.yaml
Labels: approved, lgtm, size/L

#70 MPI Backend Example
  examples/mpi-mnist/cpu/Dockerfile
  examples/mpi-mnist/cpu/mpi_mnist_cpu.py
  examples/mpi-mnist/cpu/v1alpha2/mpi_mnist_job_cpu.yaml
  examples/mpi-mnist/gpu/Dockerfile
  examples/mpi-mnist/gpu/README.md
  examples/mpi-mnist/gpu/mpi_mnist_gpu.py
  examples/mpi-mnist/gpu/v1alpha2/mpi_mnist_job_gpu.yaml
Labels: approved, lgtm, size/L

#77 Restructing examples folder
  examples/ddp/mnist/cpu/Dockerfile
  examples/ddp/mnist/cpu/mnist_DDP_CPU.py
  examples/ddp/mnist/cpu/v1alpha2/job_mnist_DDP_CPU.yaml
  examples/gloo-dist/mnist/Dockerfile
  examples/gloo-dist/mnist/dist_mnist.py
  examples/gloo-dist/mnist/v1alpha2/pytorch_job_mnist.yaml
  examples/mpi-dist/mnist/cpu/Dockerfile
  examples/mpi-dist/mnist/cpu/mpi_mnist_cpu.py
  examples/mpi-dist/mnist/cpu/v1alpha2/mpi_mnist_job_cpu.yaml
  examples/mpi-dist/mnist/gpu/Dockerfile
  examples/mpi-dist/mnist/gpu/README.md
  examples/mpi-dist/mnist/gpu/mpi_mnist_gpu.py
  examples/mpi-dist/mnist/gpu/v1alpha2/mpi_mnist_job_gpu.yaml
  examples/smoke-dist/Dockerfile
  examples/smoke-dist/README.md
  examples/smoke-dist/dist_sendrecv.py
  examples/smoke-dist/v1alpha1/pytorch_job_sendrecv.yaml
  examples/smoke-dist/v1alpha2/pytorch_job_sendrecv.yaml
  examples/tcp-dist/cifar10/README.md
  examples/tcp-dist/cifar10/configmap_cifar.yaml
  examples/tcp-dist/cifar10/pytorchjob_cifar.yaml
  examples/tcp-dist/mnist/Dockerfile
  examples/tcp-dist/mnist/Makefile
  examples/tcp-dist/mnist/README.md
  examples/tcp-dist/mnist/dist_mnist.py
  examples/tcp-dist/mnist/v1alpha1/pytorch_job_mnist.yaml
  examples/tcp-dist/mnist/v1alpha2/pytorch_job_mnist.yaml
  scripts/build.sh
Labels: approved, lgtm, size/S

#79 Adding pytorch 0.4 as default
  examples/gloo-dist/mnist/Dockerfile
  examples/gloo-dist/mnist/dist_mnist.py
  examples/smoke-dist/Dockerfile
  examples/tcp-dist/mnist/Dockerfile
  examples/tcp-dist/mnist/dist_mnist.py
Labels: approved, lgtm, size/S

#80 Updating Readme
  README.md
Labels: approved, lgtm, size/L

#82 Changing example filename to lowercase
  examples/ddp/mnist/cpu/Dockerfile
  examples/ddp/mnist/cpu/mnist_ddp_cpu.py
  examples/ddp/mnist/gpu/Dockerfile
  examples/ddp/mnist/gpu/mnist_ddp_gpu.py
Labels: approved, lgtm, size/XS

#83 Remove unnecessary char
  examples/tcp-dist/cifar10/v1alpha1/pytorch_job_cifar.yaml
Labels: approved, lgtm, size/XS
