Repository kubeflow/pytorch-operator, pull requests merged in 2018-04, with the labels that each got.

#21 Unbuffered python for realtime logs
  README.md
  pkg/trainer/replicas.go
  pkg/trainer/replicas_test.go
Labels: approved, lgtm, size/S

#22 Example now reaches Succeeded state
  pkg/controller/controller.go
  pkg/trainer/replicas.go
  pkg/trainer/replicas_test.go
  pkg/trainer/training.go
  pkg/trainer/training_test.go
  pkg/util/retryutil/retry_util.go
  pkg/util/util_test.go
  test/e2e/main.go
Labels: approved, lgtm, size/L

#19 Add gcloudignore
  .gcloudignore
Labels: approved, lgtm, size/XS

#18 Add glide files
  glide.lock
  glide.yaml
Labels: approved, lgtm, size/L

#23 Added distributed CIFAR-10 example
  README.md
  examples/README.md
  examples/cifar10/configmap_cifar.yaml
  examples/cifar10/pytorchjob_cifar.yaml
  examples/dist_train.py
  examples/mnist/configmap.yaml
  examples/mnist/pytorchjob.yaml
  examples/multinode/pytorch-master-svc.yaml
  examples/multinode/pytorch-master.yaml
  examples/multinode/pytorch-worker.yaml
  examples/multinode/pytorch-worker2.yaml
  examples/singlenode/pytorch-mnist.yaml
  scripts/run-tests.sh
  test/e2e/main.go
Labels: approved, lgtm, size/XL

#27 Replace kubeflow-images-staging with kubeflow-images-public
  test/workflows/environments/releasing/params.libsonnet
Labels: approved, lgtm, size/XS
