Repository kubeflow/pytorch-operator, pull requests merged in 2018-11, with the labels that each got.

#93 Pytorch operator v1beta1 APIs
  Gopkg.lock
  Gopkg.toml
  hack/update-codegen.sh
  pkg/apis/pytorch/v1beta1/constants.go
  pkg/apis/pytorch/v1beta1/defaults.go
  pkg/apis/pytorch/v1beta1/doc.go
  pkg/apis/pytorch/v1beta1/register.go
  pkg/apis/pytorch/v1beta1/types.go
  pkg/apis/pytorch/v1beta1/zz_generated.deepcopy.go
  pkg/apis/pytorch/v1beta1/zz_generated.defaults.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/kubeflow/v1beta1/doc.go
  pkg/client/clientset/versioned/typed/kubeflow/v1beta1/fake/doc.go
  pkg/client/clientset/versioned/typed/kubeflow/v1beta1/fake/fake_kubeflow_client.go
  pkg/client/clientset/versioned/typed/kubeflow/v1beta1/fake/fake_pytorchjob.go
  pkg/client/clientset/versioned/typed/kubeflow/v1beta1/generated_expansion.go
  pkg/client/clientset/versioned/typed/kubeflow/v1beta1/kubeflow_client.go
  pkg/client/clientset/versioned/typed/kubeflow/v1beta1/pytorchjob.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/kubeflow/interface.go
  pkg/client/informers/externalversions/kubeflow/v1beta1/interface.go
  pkg/client/informers/externalversions/kubeflow/v1beta1/pytorchjob.go
  pkg/client/listers/kubeflow/v1beta1/expansion_generated.go
  pkg/client/listers/kubeflow/v1beta1/pytorchjob.go
  pkg/controller.v2/pytorch/job.go
  pkg/trainer/training.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/common/v1beta1/common_types.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/common/v1beta1/openapi_generated.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/common/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/common/v1beta1/zz_generated.defaults.go
  vendor/github.com/kubeflow/tf-operator/pkg/controller.v2/jobcontroller/jobcontroller.go
  vendor/k8s.io/kube-openapi/cmd/openapi-gen/args/args.go
  vendor/k8s.io/kube-openapi/pkg/common/common.go
  vendor/k8s.io/kube-openapi/pkg/generators/api_linter.go
  vendor/k8s.io/kube-openapi/pkg/generators/extension.go
  vendor/k8s.io/kube-openapi/pkg/generators/openapi.go
  vendor/k8s.io/kube-openapi/pkg/generators/rules/doc.go
  vendor/k8s.io/kube-openapi/pkg/generators/rules/names_match.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/document.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/openapi.go
  vendor/k8s.io/kube-openapi/pkg/util/sets/empty.go
  vendor/k8s.io/kube-openapi/pkg/util/sets/string.go
Labels: approved, lgtm, size/XXL

#94 Validation test for V1beta1 apis
  pkg/apis/pytorch/validation/validation.go
  pkg/apis/pytorch/validation/validation_test.go
Labels: approved, lgtm, size/L

#95 Updating common JobController vendor
  Gopkg.lock
  vendor/github.com/kubeflow/tf-operator/pkg/common/jobcontroller/jobcontroller.go
  vendor/github.com/kubeflow/tf-operator/pkg/common/jobcontroller/pod.go
  vendor/github.com/kubeflow/tf-operator/pkg/common/jobcontroller/service.go
  vendor/github.com/kubeflow/tf-operator/pkg/common/jobcontroller/util.go
Labels: approved, lgtm, size/XL

#97 Adding controller for v1beta1 api
  .travis.yml
  cmd/pytorch-operator.v1beta1/app/options/options.go
  cmd/pytorch-operator.v1beta1/app/server.go
  cmd/pytorch-operator.v1beta1/main.go
  pkg/common/util/testutil/const.go
  pkg/common/util/testutil/job.go
  pkg/common/util/testutil/pod.go
  pkg/common/util/testutil/service.go
  pkg/common/util/testutil/util.go
  pkg/common/util/unstructured/informer.go
  pkg/controller.v1beta1/pytorch/controller.go
  pkg/controller.v1beta1/pytorch/controller_test.go
  pkg/controller.v1beta1/pytorch/informer.go
  pkg/controller.v1beta1/pytorch/job.go
  pkg/controller.v1beta1/pytorch/job_test.go
  pkg/controller.v1beta1/pytorch/pod.go
  pkg/controller.v1beta1/pytorch/pod_test.go
  pkg/controller.v1beta1/pytorch/service.go
  pkg/controller.v1beta1/pytorch/service_test.go
  pkg/controller.v1beta1/pytorch/status.go
  pkg/controller.v1beta1/pytorch/status_test.go
  pkg/controller.v1beta1/pytorch/util.go
  pkg/controller.v1beta1/pytorch/util_test.go
Labels: approved, lgtm, size/XXL

#98 Adding examples for v1beta1 API
  examples/ddp/mnist/cpu/v1beta1/job_mnist_ddp_cpu.yaml
  examples/ddp/mnist/gpu/v1beta1/job_mnist_ddp_gpu.yaml
  examples/gloo-dist/mnist/v1beta1/pytorch_job_mnist.yaml
  examples/mpi-dist/mnist/cpu/v1beta1/mpi_mnist_job_cpu.yaml
  examples/mpi-dist/mnist/gpu/v1beta1/mpi_mnist_job_gpu.yaml
  examples/smoke-dist/v1beta1/pytorch_job_sendrecv.yaml
  examples/tcp-dist/cifar10/v1beta1/pytorch_job_cifar.yaml
  examples/tcp-dist/mnist/v1beta1/pytorch_job_mnist.yaml
Labels: approved, lgtm, size/L

#99 Ensure that PyTorch CRD exists
  Gopkg.lock
  Gopkg.toml
  cmd/pytorch-operator.v1beta1/app/options/options.go
  cmd/pytorch-operator.v1beta1/app/server.go
  pkg/apis/pytorch/v1beta1/register.go
  pkg/controller.v1beta1/pytorch/job.go
  pkg/controller.v1beta1/pytorch/pod.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/helpers.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/generated_expansion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/features/kube_features.go
Labels: approved, lgtm, size/XXL

#100 Release image to kubeflow images public
  prow_config.yaml
Labels: approved, lgtm, size/S

#102 Fix registry override for image builds
  prow_config.yaml
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/S

#106 Keeping default project as kubeflow-ci
  prow_config.yaml
Labels: approved, lgtm, size/XS

#107 gopkg: Use version instead of branch
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
Labels: approved, lgtm, size/L

#101 Adding e2e tests for v1beta1
  scripts/v1alpha2/delete-v1alpha2.sh
  scripts/v1beta1/delete-v1beta1.sh
  scripts/v1beta1/run-cleanpodpolicy-all.sh
  scripts/v1beta1/run-defaults.sh
  scripts/v1beta1/setup-v1beta1.sh
  test/e2e/v1beta1/cleanpolicy_all.go
  test/e2e/v1beta1/defaults.go
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XL
