Repository kubeflow/pytorch-operator, pull requests merged in 2018-06, with the labels that each got.

#28 Add releasing instructions
  releasing.md
  submit_release_job.sh
  test/workflows/environments/releasing/params.libsonnet
Labels: lgtm, size/M

#38 E2e test image
  examples/dist-mnist/Dockerfile
  examples/dist-mnist/README.md
  examples/dist-mnist/dist_mnist.py
  examples/dist-mnist/pytorch_job_mnist.yaml
  examples/mnist/configmap.yaml
  examples/mnist/pytorchjob.yaml
  scripts/build.sh
  scripts/run-tests.sh
  test/e2e/main.go
  vendor/github.com/json-iterator/go/skip_tests/array/skip_test.go
  vendor/github.com/json-iterator/go/skip_tests/object/skip_test.go
  vendor/github.com/json-iterator/go/skip_tests/string/skip_test.go
Labels: approved, lgtm, size/L

#37 Minimal smoke test for distributed training
  examples/dist-sendrecv/Dockerfile
  examples/dist-sendrecv/README.md
  examples/dist-sendrecv/dist_sendrecv.py
  examples/dist-sendrecv/pytorch_job_sendrecv.yaml
  scripts/build.sh
  scripts/run-tests.sh
  test/e2e/main.go
Labels: approved, lgtm, size/L

#39 Adding build_image.sh file for nightly releases
  build_image.sh
Labels: approved, lgtm, size/S

#41 Minor fix to export the GOPATH variable
  build_image.sh
Labels: approved, lgtm, size/XS

#43 make build_image.sh executable
  build_image.sh
Labels: approved, lgtm, size/XS

#45 Updating Readme
  README.md
Labels: approved, lgtm, size/L

#46 Adding to owners
  OWNERS
Labels: approved, lgtm, size/XS

#44 Changing from helm to ksonnet install
  scripts/run-tests.sh
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/M
