Repository kubeflow/pytorch-operator, pull requests merged in 2018-12, with the labels that each got.

#112 Pytorch Katib example
  examples/katib/Dockerfile
  examples/katib/mnist_with_summary.py
  examples/katib/pytorch_job_mnist.yaml
Labels: approved, lgtm, size/L

#113 Update k8s cluster version to 1.10
  scripts/create-cluster.sh
Labels: approved, lgtm, size/XS

#116 Add master role label for PyTorchJob
  pkg/controller.v1beta1/pytorch/controller.go
  pkg/controller.v1beta1/pytorch/pod.go
Labels: approved, lgtm, size/S

#115 Minor fixes
  pkg/controller.v1beta1/pytorch/controller.go
  pkg/controller.v1beta1/pytorch/informer.go
  pkg/controller.v1beta1/pytorch/job.go
  pkg/controller.v2/pytorch/controller.go
  pkg/controller.v2/pytorch/informer.go
  pkg/controller.v2/pytorch/job.go
Labels: approved, lgtm, size/M

#114 GetCondition func fix
  pkg/controller.v1beta1/pytorch/status.go
  pkg/controller.v2/pytorch/status.go
Labels: approved, lgtm, size/S

#121 Updated gcloud build related code.
  build_image.sh
  scripts/build.sh
Labels: approved, lgtm, ok-to-test, size/XS
