Repository kubeflow/pytorch-operator, pull requests merged in 2019-08, with the labels that each got.

#194 feat: Support running although it is uesless
  pkg/controller.v1/pytorch/job.go
  pkg/controller.v1beta2/pytorch/job.go
Labels: approved, lgtm, size/S

#201 add total suffix in counter metrics
  docs/monitoring/README.md
  pkg/controller.v1/pytorch/controller.go
  pkg/controller.v1/pytorch/job.go
  pkg/controller.v1/pytorch/status.go
Labels: approved, lgtm, ok-to-test, size/S

#198 Use multi-build to build pytorch-operator image
  .gcloudignore
  Dockerfile
  scripts/build.sh
Labels: approved, lgtm, ok-to-test, size/S

#200 Update manifest to v0.6.0
  manifests/deployment.yaml
  manifests/rbac.yaml
  manifests/service.yaml
Labels: approved, lgtm, size/S

#207 Update codegen and verify in CI
  .travis.yml
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/controller.v1/pytorch/controller.go
  pkg/controller.v1beta2/pytorch/controller.go
Labels: approved, lgtm, ok-to-test, size/M

#208 Set pytorchjob defaults in test utils
  pkg/common/util/v1/testutil/job.go
  pkg/common/util/v1beta2/testutil/job.go
Labels: approved, lgtm, ok-to-test, size/XS

#210 Add qps and burst options
  cmd/pytorch-operator.v1/app/options/options.go
  cmd/pytorch-operator.v1/app/server.go
  cmd/pytorch-operator.v1beta2/app/options/options.go
  cmd/pytorch-operator.v1beta2/app/server.go
Labels: approved, lgtm, ok-to-test, size/S
