Repository kubeflow/pytorch-operator, pull requests merged in 2019-12, with the labels that each got.

#227 Generate Kubeflow PyTorchJob SDK
  hack/python-sdk/gen-sdk.sh
  hack/python-sdk/main.go
  hack/python-sdk/swagger_config.json
  pkg/apis/pytorch/v1/doc.go
  pkg/apis/pytorch/v1/openapi_generated.go
  scripts/setup-kubeflow.sh
  sdk/python/.gitignore
  sdk/python/OWNERS
  sdk/python/README.md
  sdk/python/docs/PyTorchJobClient.md
  sdk/python/docs/V1JobCondition.md
  sdk/python/docs/V1JobStatus.md
  sdk/python/docs/V1PyTorchJob.md
  sdk/python/docs/V1PyTorchJobList.md
  sdk/python/docs/V1PyTorchJobSpec.md
  sdk/python/docs/V1ReplicaSpec.md
  sdk/python/docs/V1ReplicaStatus.md
  sdk/python/docs/V1Time.md
  sdk/python/examples/kubeflow-pytorchjob-sdk.ipynb
  sdk/python/kubeflow/__init__.py
  sdk/python/kubeflow/pytorchjob/__init__.py
  sdk/python/kubeflow/pytorchjob/api/__init__.py
  sdk/python/kubeflow/pytorchjob/api/py_torch_job_client.py
  sdk/python/kubeflow/pytorchjob/api_client.py
  sdk/python/kubeflow/pytorchjob/configuration.py
  sdk/python/kubeflow/pytorchjob/constants/__init__.py
  sdk/python/kubeflow/pytorchjob/constants/constants.py
  sdk/python/kubeflow/pytorchjob/models/__init__.py
  sdk/python/kubeflow/pytorchjob/models/v1_job_condition.py
  sdk/python/kubeflow/pytorchjob/models/v1_job_status.py
  sdk/python/kubeflow/pytorchjob/models/v1_py_torch_job.py
  sdk/python/kubeflow/pytorchjob/models/v1_py_torch_job_list.py
  sdk/python/kubeflow/pytorchjob/models/v1_py_torch_job_spec.py
  sdk/python/kubeflow/pytorchjob/models/v1_replica_spec.py
  sdk/python/kubeflow/pytorchjob/models/v1_replica_status.py
  sdk/python/kubeflow/pytorchjob/models/v1_time.py
  sdk/python/kubeflow/pytorchjob/rest.py
  sdk/python/kubeflow/pytorchjob/utils/__init__.py
  sdk/python/kubeflow/pytorchjob/utils/utils.py
  sdk/python/requirements.txt
  sdk/python/setup.py
  sdk/python/test/__init__.py
  sdk/python/test/test_e2e.py
  sdk/python/test/test_v1_job_condition.py
  sdk/python/test/test_v1_job_status.py
  sdk/python/test/test_v1_py_torch_job.py
  sdk/python/test/test_v1_py_torch_job_list.py
  sdk/python/test/test_v1_py_torch_job_spec.py
  sdk/python/test/test_v1_replica_spec.py
  sdk/python/test/test_v1_replica_status.py
  test/e2e/v1/cleanpolicy/cleanpolicy_all.go
  test/e2e/v1/default/defaults.go
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XXL

#231 fix(job_test) test case should not include worker service
  pkg/controller.v1/pytorch/job_test.go
  vendor/github.com/kubeflow/tf-operator/pkg/control/service_control.go
Labels: approved, lgtm, ok-to-test, size/M

#233 feat(deletePodsAndServices):only delete master service
  pkg/controller.v1/pytorch/controller.go
  pkg/controller.v1/pytorch/job.go
  vendor/github.com/kubeflow/tf-operator/pkg/control/service_control.go
Labels: approved, lgtm, ok-to-test, size/S

#238 replace gopkg.in/yaml.v2 with github.com/kubernetes-sigs/yaml repo
  Gopkg.lock
  Gopkg.toml
  pkg/controller.v1/pytorch/util.go
  vendor/github.com/kubernetes-sigs/yaml/LICENSE
  vendor/github.com/kubernetes-sigs/yaml/fields.go
  vendor/github.com/kubernetes-sigs/yaml/yaml.go
  vendor/github.com/kubernetes-sigs/yaml/yaml_go110.go
Labels: approved, lgtm, ok-to-test, size/XXL

#235 fix(*) rm work service in controller_test.go
  pkg/controller.v1/pytorch/controller_test.go
Labels: approved, lgtm, ok-to-test, size/S

#242 fix the reconcile flow
  pkg/controller.v1/pytorch/controller.go
Labels: approved, lgtm, size/L

#241 ConvertPyTorchJobToUnstructured uses function ToUnstructured to convert PyTorchJob to Unstructured instead of json
  pkg/common/util/v1/testutil/util.go
Labels: approved, lgtm, ok-to-test, size/S

#240 Add more APIs for SDK
  sdk/python/README.md
  sdk/python/docs/PyTorchJobClient.md
  sdk/python/examples/kubeflow-pytorchjob-sdk.ipynb
  sdk/python/kubeflow/pytorchjob/api/py_torch_job_client.py
  sdk/python/kubeflow/pytorchjob/constants/constants.py
  sdk/python/setup.py
  sdk/python/test/test_e2e.py
Labels: approved, lgtm, size/XL
