Repository kubeflow/pytorch-operator, pull requests merged in 2019-09, with the labels that each got.

#213 Minor change in log
  pkg/common/config/config.go
Labels: approved, lgtm, size/XS

#216 Fix nslookup cannot work well in initContainerTemplate
  pkg/common/config/config.go
Labels: approved, lgtm, size/XS

#218 add mnist example dockerfile for ppc64le
  examples/mnist/Dockerfile.ppc64le
  examples/mnist/README.md
Labels: approved, lgtm, ok-to-test, size/S

#221 Removing unnecessary rbac permissions
  manifests/rbac.yaml
Labels: approved, lgtm, size/S

#220 Avoiding unnecessary status update
  pkg/controller.v1/pytorch/controller.go
Labels: approved, lgtm, size/XS
