Repository kubeflow/pytorch-operator, pull requests merged in 2019-06, with the labels that each got.

#169 Making ResyncPeriod configurable
  cmd/pytorch-operator.v1/app/options/options.go
  cmd/pytorch-operator.v1/app/server.go
Labels: approved, lgtm, size/S

#171 Check pending status for pastBackoffLimitOnFailure
  pkg/controller.v1/pytorch/controller.go
  pkg/controller.v1beta2/pytorch/controller.go
Labels: approved, lgtm, size/M

#173 Skip condition update when succeeded
  pkg/controller.v1/pytorch/status.go
  pkg/controller.v1beta2/pytorch/status.go
Labels: approved, lgtm, size/XS

#172 Sync PodGroup fix
  Gopkg.lock
  Gopkg.toml
  pkg/controller.v1/pytorch/controller.go
  pkg/controller.v1beta2/pytorch/controller.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/common/v1/openapi_generated.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/common/v1/types.go
  vendor/github.com/kubeflow/tf-operator/pkg/common/jobcontroller/jobcontroller.go
  vendor/github.com/kubeflow/tf-operator/pkg/common/jobcontroller/pod.go
Labels: approved, lgtm, size/L

#170 Set start timestamp
  pkg/controller.v1/pytorch/status.go
  pkg/controller.v1beta2/pytorch/status.go
Labels: approved, lgtm, size/XS

#176 Update image base to UBI8 GA
  Dockerfile
Labels: approved, lgtm, size/XS

#177 Adds developer guide and sample CRD for v1
  README.md
  developer_guide.md
  examples/crd/crd-v1.yaml
Labels: approved, lgtm, ok-to-test, size/L

#178 Moving crd to manifests
  developer_guide.md
  examples/crd/crd-v1.yaml
  manifests/crd.yaml
Labels: approved, lgtm, size/M

#179 fix wrong api version when delete pytorchjob
  pkg/controller.v1/pytorch/job.go
Labels: approved, lgtm, size/XS

#181 set annotation automatically when EnableGangScheduling is set to true…
  pkg/controller.v1/pytorch/pod.go
Labels: approved, lgtm, ok-to-test, size/XS
