Repository kubeflow/pytorch-operator, pull requests merged in 2019-07, with the labels that each got.

#189 update release script; fix post submit
  scripts/create-cluster.sh
  scripts/setup-kubeflow.sh
  submit_release_job.sh
  test/workflows/app.yaml
  test/workflows/components/workflows.libsonnet
  test/workflows/environments/test/params.libsonnet
Labels: approved, lgtm, size/M

#184 Minor fix to add CoreV1 to scheme
  cmd/pytorch-operator.v1/app/server.go
Labels: approved, lgtm, size/XS

#187 use init container for worker pod to wait master pod ready
  pkg/common/config/config.go
  pkg/controller.v1/pytorch/controller_test.go
  pkg/controller.v1/pytorch/pod.go
  pkg/controller.v1/pytorch/util.go
  pkg/controller.v1/pytorch/util_test.go
Labels: approved, lgtm, ok-to-test, size/L

#191 Remove unnecessary services for worker
  pkg/apis/pytorch/v1/defaults.go
  pkg/controller.v1/pytorch/controller.go
  pkg/controller.v1/pytorch/controller_test.go
Labels: approved, lgtm, size/S

#193 fix: Fix the comments
  pkg/apis/pytorch/v1/defaults.go
  pkg/apis/pytorch/v1/types.go
  pkg/apis/pytorch/v1beta2/defaults.go
  pkg/apis/pytorch/v1beta2/types.go
Labels: approved, lgtm, size/S

#192 add kubeconfig flag
  cmd/pytorch-operator.v1/app/options/options.go
  cmd/pytorch-operator.v1beta2/app/options/options.go
Labels: approved, lgtm, ok-to-test, size/XS
