Repository kubeflow/pytorch-operator, pull requests merged in 2019-03, with the labels that each got.

#142 Change cluster version to 1.11
  scripts/create-cluster.sh
Labels: approved, lgtm, size/XS

#141 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#145 Workers are created only when the master is in running phase
  pkg/controller.v1beta2/pytorch/controller_test.go
  pkg/controller.v1beta2/pytorch/pod.go
Labels: approved, lgtm, size/M

#146 Renaming labels to consistent format
  README.md
  pkg/common/util/v1beta1/testutil/util.go
  pkg/common/util/v1beta2/testutil/util.go
  pkg/controller.v1beta1/pytorch/controller.go
  pkg/controller.v1beta1/pytorch/controller_test.go
  pkg/controller.v1beta2/pytorch/controller.go
  pkg/controller.v1beta2/pytorch/controller_test.go
  test/e2e/v1beta1/cleanpolicy_all.go
Labels: approved, lgtm, size/M

#147 Update tests to have single operator deployment for v1beta1 and v1beta2 API
  pkg/controller.v1beta2/pytorch/pod.go
  scripts/setup-kubeflow.sh
  scripts/v1beta1/delete-v1beta1.sh
  scripts/v1beta1/setup-v1beta1.sh
  scripts/v1beta2/delete-v1beta2.sh
  scripts/v1beta2/setup-v1beta2.sh
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#148 Remove usage of crd client
  cmd/pytorch-operator.v1beta2/app/server.go
  pkg/common/util/v1beta2/unstructured/informer.go
Labels: approved, lgtm, size/M

#149 Use kube-batch as scheduler by default when gang-scheduling is enabled
  pkg/controller.v1beta2/pytorch/pod.go
Labels: approved, lgtm, size/S

#150 Use podGroup instead of PDB in v1beta2
  Gopkg.lock
  Gopkg.toml
  cmd/pytorch-operator.v1beta1/app/server.go
  cmd/pytorch-operator.v1beta2/app/server.go
  manifests/podgroup.yaml
  pkg/controller.v1beta1/pytorch/controller.go
  pkg/controller.v1beta1/pytorch/controller_test.go
  pkg/controller.v1beta1/pytorch/job_test.go
  pkg/controller.v1beta1/pytorch/pod_test.go
  pkg/controller.v1beta1/pytorch/service_test.go
  pkg/controller.v1beta1/pytorch/status_test.go
  pkg/controller.v1beta2/pytorch/controller.go
  pkg/controller.v1beta2/pytorch/controller_test.go
  pkg/controller.v1beta2/pytorch/job_test.go
  pkg/controller.v1beta2/pytorch/pod_test.go
  pkg/controller.v1beta2/pytorch/service_test.go
  pkg/controller.v1beta2/pytorch/status_test.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/common/v1beta1/doc.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/common/v1beta1/openapi_generated.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/common/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/common/v1beta2/doc.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/common/v1beta2/openapi_generated.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/common/v1beta2/types.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/common/v1beta2/zz_generated.deepcopy.go
  vendor/github.com/kubeflow/tf-operator/pkg/common/jobcontroller/jobcontroller.go
  vendor/github.com/kubernetes-sigs/kube-batch/LICENSE
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/apis/scheduling/v1alpha1/doc.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/apis/scheduling/v1alpha1/labels.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/apis/scheduling/v1alpha1/register.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/apis/scheduling/v1alpha1/types.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/client/clientset/versioned/clientset.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/client/clientset/versioned/doc.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/client/clientset/versioned/scheme/doc.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/client/clientset/versioned/typed/scheduling/v1alpha1/doc.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/client/clientset/versioned/typed/scheduling/v1alpha1/generated_expansion.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/client/clientset/versioned/typed/scheduling/v1alpha1/podgroup.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/client/clientset/versioned/typed/scheduling/v1alpha1/queue.go
  vendor/github.com/kubernetes-sigs/kube-batch/pkg/client/clientset/versioned/typed/scheduling/v1alpha1/scheduling_client.go
Labels: approved, lgtm, size/XXL

#151 Implement ActiveDeadlineSeconds and BackoffLimit
  Gopkg.lock
  pkg/apis/pytorch/v1beta2/types.go
  pkg/apis/pytorch/v1beta2/zz_generated.deepcopy.go
  pkg/common/util/v1beta2/testutil/job.go
  pkg/common/util/v1beta2/testutil/pod.go
  pkg/controller.v1beta2/pytorch/controller.go
  pkg/controller.v1beta2/pytorch/controller_test.go
  pkg/controller.v1beta2/pytorch/job.go
  pkg/controller.v1beta2/pytorch/job_test.go
  pkg/controller.v1beta2/pytorch/status.go
  vendor/github.com/kubeflow/tf-operator/pkg/util/k8sutil/k8sutil.go
Labels: approved, lgtm, size/XL
