Repository kubeflow/pytorch-operator, pull requests merged in 2019-05, with the labels that each got.

#157 Prune owners file
  OWNERS
Labels: approved, lgtm, size/XS

#155 Minor format changes
  pkg/apis/pytorch/validation/validation.go
  pkg/apis/pytorch/validation/validation_test.go
  pkg/controller.v1beta1/pytorch/controller.go
  pkg/controller.v1beta2/pytorch/controller.go
Labels: approved, lgtm, size/M

#156 Set tf operator version to v0.5.0
  Gopkg.lock
  Gopkg.toml
Labels: approved, lgtm, size/XS

#158 set CompletionTime first when pytorchjob exceeds limit
  pkg/controller.v1beta2/pytorch/controller.go
Labels: approved, lgtm, ok-to-test, size/S

#159 Revise API version to v1beta2
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#165 Adding tests for operator v1 api
  scripts/v1/run-cleanpodpolicy-all.sh
  scripts/v1/run-defaults.sh
  test/e2e/v1/cleanpolicy_all.go
  test/e2e/v1/defaults.go
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/M

#164 Adding examples for v1 api
  README.md
  examples/mnist/v1/pytorch_job_mnist_gloo.yaml
  examples/mnist/v1/pytorch_job_mnist_mpi.yaml
  examples/mnist/v1/pytorch_job_mnist_nccl.yaml
Labels: approved, lgtm, size/L

#167 Polish documentation for PyTorch V1
  pkg/apis/pytorch/v1/types.go
Labels: approved, lgtm, size/M

#168 add uuid to id for leader election
  Gopkg.lock
  cmd/pytorch-operator.v1/app/server.go
  vendor/github.com/google/uuid/CONTRIBUTORS
  vendor/github.com/google/uuid/LICENSE
  vendor/github.com/google/uuid/dce.go
  vendor/github.com/google/uuid/doc.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/util.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version1.go
  vendor/github.com/google/uuid/version4.go
  vendor/github.com/pborman/uuid/CONTRIBUTORS
  vendor/github.com/pborman/uuid/LICENSE
  vendor/github.com/pborman/uuid/dce.go
  vendor/github.com/pborman/uuid/doc.go
  vendor/github.com/pborman/uuid/hash.go
  vendor/github.com/pborman/uuid/marshal.go
  vendor/github.com/pborman/uuid/node.go
  vendor/github.com/pborman/uuid/sql.go
  vendor/github.com/pborman/uuid/time.go
  vendor/github.com/pborman/uuid/util.go
  vendor/github.com/pborman/uuid/uuid.go
  vendor/github.com/pborman/uuid/version1.go
  vendor/github.com/pborman/uuid/version4.go
  vendor/k8s.io/apimachinery/pkg/util/uuid/uuid.go
Labels: approved, lgtm, needs-ok-to-test, size/XXL
