Repository kubeflow/pytorch-operator, pull requests merged in 2020-07, with the labels that each got.

#288 support cleanPodPolicy is Running, same as tf operator
  pkg/controller.v1/pytorch/job.go
  pkg/controller.v1/pytorch/job_test.go
Labels: approved, lgtm, ok-to-test, size/M

#289 Update CRD link
  README.md
Labels: approved, lgtm, size/XS

#290 Update README.md
  examples/mnist/README.md
Labels: approved, lgtm, size/XS

#274 Update openapi-gen to not rely on vendor
  Dockerfile
  go.mod
  go.sum
  hack/python-sdk/gen-sdk.sh
  pkg/apis/pytorch/v1/openapi_generated.go
Labels: approved, lgtm, size/L
