Repository kubeflow/pytorch-operator, pull requests merged in 2020-01, with the labels that each got.

#246 Add watch function for PyTorchJob python Client API
  pkg/apis/pytorch/v1/openapi_generated.go
  pkg/apis/pytorch/v1/types.go
  pkg/apis/pytorch/v1/zz_generated.deepcopy.go
  pkg/apis/pytorch/v1/zz_generated.defaults.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/pytorch/v1/doc.go
  pkg/client/clientset/versioned/typed/pytorch/v1/fake/doc.go
  pkg/client/clientset/versioned/typed/pytorch/v1/fake/fake_pytorch_client.go
  pkg/client/clientset/versioned/typed/pytorch/v1/fake/fake_pytorchjob.go
  pkg/client/clientset/versioned/typed/pytorch/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/pytorch/v1/pytorch_client.go
  pkg/client/clientset/versioned/typed/pytorch/v1/pytorchjob.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/pytorch/interface.go
  pkg/client/informers/externalversions/pytorch/v1/interface.go
  pkg/client/informers/externalversions/pytorch/v1/pytorchjob.go
  pkg/client/listers/pytorch/v1/expansion_generated.go
  pkg/client/listers/pytorch/v1/pytorchjob.go
  sdk/python/docs/PyTorchJobClient.md
  sdk/python/examples/kubeflow-pytorchjob-sdk.ipynb
  sdk/python/kubeflow/pytorchjob/api/py_torch_job_client.py
  sdk/python/kubeflow/pytorchjob/api/py_torch_job_watch.py
  sdk/python/requirements.txt
  sdk/python/setup.py
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#250 Add third party license info
  Dockerfile
  third_party/library/license.txt
  third_party_licenses/additional_license_info.csv
  third_party_licenses/dep.txt
  third_party_licenses/license_info.csv
  third_party_licenses/repo.txt
Labels: approved, lgtm, size/XXL

#251 Copy third party vendor source code to Docker image
  Dockerfile
  scripts/create-cluster.sh
Labels: approved, lgtm, size/XS

#253 fix: Add resource limits for init container
  pkg/common/config/config.go
Labels: approved, lgtm, size/XS

#252 SDK supports getting PyTorchJob training process or logs
  sdk/python/README.md
  sdk/python/docs/PyTorchJobClient.md
  sdk/python/examples/kubeflow-pytorchjob-sdk.ipynb
  sdk/python/kubeflow/pytorchjob/api/py_torch_job_client.py
  sdk/python/kubeflow/pytorchjob/constants/constants.py
  sdk/python/kubeflow/pytorchjob/utils/utils.py
  sdk/python/setup.py
  sdk/python/test/test_e2e.py
Labels: approved, lgtm, size/L

#255 Added The Pytorch GPU Docker under the appropriate folder
  examples/pytorch_cuda_docker/Dockerfile
Labels: approved, lgtm, ok-to-test, size/M
