Repository kubeflow/pytorch-operator, pull requests merged in 2020-06, with the labels that each got.

#276 Fix minor OpenShift issues - resource requests, Dockerfile
  examples/mnist/Dockerfile
  manifests/rbac.yaml
  pkg/common/config/config.go
Labels: approved, lgtm, size/S

#280 Update swagger-codegen-cli URL
  hack/python-sdk/gen-sdk.sh
Labels: approved, lgtm, size/XS

#277 fix Dockerfile-mpi download miniconda.sh
  examples/mnist/Dockerfile-mpi
Labels: approved, lgtm, ok-to-test, size/XS

#286 chore: Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#285 Adds notes and example annotation for pytorch job
  examples/mnist/README.md
  examples/mnist/v1/pytorch_job_mnist_gloo.yaml
  examples/mnist/v1/pytorch_job_mnist_mpi.yaml
  examples/mnist/v1/pytorch_job_mnist_nccl.yaml
Labels: approved, lgtm, size/S
