Repository kubeflow/pytorch-operator, pull requests merged in 2021-06, with the labels that each got.

#336 Adding example config file
  examples/smoke-dist/pytorch_job_sendrecv.yaml
Labels: approved, lgtm, size/S

#338 Add job namespace to `pytorch_operator_jobs_*` counters
  pkg/controller.v1/pytorch/controller.go
  pkg/controller.v1/pytorch/job.go
  pkg/controller.v1/pytorch/status.go
Labels: approved, lgtm, ok-to-test, size/M

#337 Bert example with Pytorch Lightning
  examples/bert/Dockerfile
  examples/bert/README.md
  examples/bert/bert.py
  examples/bert/pytorch_job_bert.yaml
Labels: approved, lgtm, size/XL
